export const DEVELOPMENT_LOG = [
  {
    module: 'Module 00',
    title: 'Shared Types and Constants',
    checklist: [
      'Shared types created under src/types',
      'Shared constants created under src/constants',
      'Barrel exports available for imports',
      'Approximate USF campus boundary added',
      'Loop, grid, and points rules defined',
      'Expo Go screen updated to show Module 00 status',
    ],
  },
  {
    module: 'Module 01',
    title: 'Geometry Engine',
    checklist: [
      'Pure TypeScript geometry helpers exported from src/lib/geometry/index.ts',
      'Haversine distance and full path distance calculations added',
      'Closed-loop detection validates distance, closure, point count, and area',
      'Campus grid cells now include center coordinates and polygon corners',
      'Cell selection filters grid cells by polygon containment',
      'Expo Go screen renders live Module 01 geometry status',
    ],
  },
  {
    module: 'Module 02',
    title: 'Territory Engine',
    checklist: [
      'Pure TypeScript territory helpers exported from src/lib/territory/index.ts',
      'Claim score now combines base points, distance, area, and capped pace bonus',
      'Valid run sessions can be converted into scored territory claims',
      'Claims apply only to cells whose centers fall inside the claim polygon',
      'Ownership resolves by highest score while keeping runner-up overlap data',
      'Expo Go screen renders a visible Module 02 overlap checklist and demo',
    ],
  },
  {
    module: 'Module 03',
    title: 'Demo Mode',
    checklist: [
      'Mock demo groups, paths, issues, and sightings live under src/demo',
      'Demo scenario runs without GPS, Supabase, or live services',
      'Campus grid, valid loop claims, and overlap resolution are assembled together',
      'Returned demo payload includes groups, cells, claims, scores, ownership, issues, and sightings',
      'Group B wins contested cells while Group A keeps non-overlapped territory',
      'Expo Go screen renders a visible Module 03 demo-mode checklist and snapshot',
    ],
  },
  {
    module: 'Module 04',
    title: 'Map Rendering',
    checklist: [
      'Campus boundary renders from shared campus coordinates',
      'Territory cells render in owning group colors',
      'Overlapping ownership from the demo scenario appears on the map',
      'Demo run paths, issues, sightings, and a user marker render together',
      'Map layers stay prop-driven and do not calculate game logic',
      'Expo Go opens to a visible Module 04 checklist and working map',
    ],
  },
  {
    module: 'Module 05',
    title: 'Pixel Art Layer',
    checklist: [
      'Pixel art rules only allow painting currently owned cells',
      'A color picker and paint toolbar render above the live map',
      'Tapping owned cells paints them with the selected color',
      'Rival-owned cells reject paint attempts',
      'Painted cells appear as a separate overlay on the map',
      'Expo Go shows a visible Module 05 checklist and working paint flow',
    ],
  },
  {
    module: 'Module 06',
    title: 'Issues: Reporting & Fixing',
    checklist: [
      'Issue reporting and fixing use local/demo state first',
      'Issue form supports title, category, description, coordinate, and mock photo fallback',
      'Issue cards show category, description, before and after photo URIs, and status',
      'Open issue pins stay red and fixed issue pins turn green on the map',
      'Fixing an issue returns points and updates the selected issue in place',
      'Development Log tab documents Module 00 through Module 06 checklists',
    ],
  },
  {
    module: 'Module 07',
    title: 'Leaderboards & Feed',
    checklist: [
      'Feed events are built locally from demo runs, claims, issues, sightings, art, and landmarks',
      'Feed items support local likes and local comments without realtime or backend state',
      'Leaderboards rank top groups, top users, issues fixed, cells owned, and sightings added',
      'Current demo group and user can be highlighted in leaderboard rows',
      'A dedicated Feed tab shows activity and leaderboard views',
      'Development Log now documents Modules 00 through 07',
    ],
  },
  {
    module: 'Module 13',
    title: 'Campus Access & Viewport UX',
    checklist: [
      'USF Tampa viewport constants now distinguish map focus bounds from gameplay boundary',
      'Campus access helpers derive on-campus, near-campus, off-campus, and unknown states',
      'Map opens directly into a campus-focused initial region and can recenter to campus',
      'Campus mode chips and preview banners communicate on-campus versus preview behavior',
      'Preview mode still allows exploration and demo actions without blocking the whole app',
      'Development Log now documents Modules 00 through 07 plus Module 13',
    ],
  },
  {
    module: 'Module 14',
    title: 'Design System & App Shell',
    checklist: [
      'Shared theme tokens now define Runable colors, spacing, radii, shadows, and z-index',
      'Reusable UI primitives now include XP windows, chips, glossy buttons, stat tiles, and a floating action dock',
      'Map tab now uses a cleaner overlay shell with compact status, toast, sheet, and dock regions',
      'Preview mode gates campus-only actions with an explicit campus access overlay instead of silent failure',
      'Expo Router tab chrome now uses a more intentional Runable bottom navigation style',
      'Development Log now documents the Module 14 app-shell pass',
    ],
  },
  {
    module: 'Module 09',
    title: 'Real Run Tracking',
    checklist: [
      'Real GPS tracking now requests foreground location permission through Expo Location',
      'Users can start, pause, resume, finish, and cancel a live run on the map screen',
      'Live path, elapsed time, distance, and recorded GPS point count update while tracking',
      'Finished runs are checked against the existing closed-loop geometry rules',
      'Valid live loops immediately create local territory claims and update board ownership',
      'Invalid loops show clear failure reasons without breaking demo mode',
    ],
  },
  {
    module: 'Module 08',
    title: 'Supabase, Auth & Zustand Store',
    checklist: [
      'Zustand app store manages auth state, app mode, user, group, and auth gate visibility',
      'Supabase client initializes conditionally — app works without env vars in demo mode',
      'Auth services wrap sign up, sign in, sign out, and session management',
      'Profile, group, run, territory, issue, sighting, art, feed, and storage services created',
      'useAuth hook bridges Zustand store with Supabase auth and bootstraps sessions on mount',
      'Campus mode toggle requires authentication — shows XP-themed auth gate when not logged in',
      'Login, signup, group picker, and auth gate UI follow the retro XP window theme',
      'Unauthenticated users see the map in read-only preview mode',
      'Demo mode remains available without Supabase configuration',
      'Campus boundary polygon updated from rectangle to road-traced USF shape',
      'All feed, leaderboard, and dev log screens updated to use consistent XP theme tokens',
    ],
  },
  {
    module: 'Module 10',
    title: 'Sightings & Landmarks',
    checklist: [
      'Sightings data types created with strict categories (animal, plant, scenic, water, landmark, other)',
      'Sighting hooks, mock data, and local create patterns established',
      'Sighting category pickers and interactive XP-window submission forms implemented',
      'Sightings naturally render on map as distinct interactive pins',
      'Landmarks enable community naming functionality via separate Vote Card UI',
      'Map engine now distinctly handles interactive intentions like reporting vs sightseeing',
    ],
  },
  {
    module: 'Module 11',
    title: 'Game Periods & Archives',
    checklist: [
      'Active game periods determined from local 6-hour interval logic (Dawn, Day, Dusk, Night)',
      'Asynchronous snapshot architecture clones ownership, art, and metrics into historical archives',
      'Finalization orchestration validates winners from the leaderboard at resolution time',
      'Archive cards visualize historical control, trophy banners, and dominance metrics',
      'Manual MVP toggles in Development Log enable on-demand snapshot creation for demos',
      'Snapshots persist in local UI state without requiring complex cron or backend workers',
    ],
  },
] as const;
